[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "nodelab"
version = "1.0.0"
dependencies = ["pyyaml"]

[project.scripts]
nodelab = "nodelab.main:main"
